use test;

CREATE TABLE Members (
	UUID INT PRIMARY KEY AUTO_INCREMENT,
    Nickname VARCHAR(50) NOT NULL,
    Password VARCHAR(50) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Address VARCHAR(50) NOT NULL,
    ProfileUrl VARCHAR(255) NOT NULL,
    JoinDate DATETIME DEFAULT NOW() NOT NULL,
    SelfIntro VARCHAR(500) NOT NULL
);
  	SELECT
	  	 ID,
	  	 UUID,
	  	 Location,
	  	 Up,
	  	 Views,
	  	 Tag,
	  	 Title,
	  	 Content,
	  	 Inserted,
	  	 Updated
  	FROM
  	 	Please
  	 Order By
  	 	ID DESC;
ALTER TABLE Members MODIFY COLUMN JoinDate DATETIME DEFAULT NOW() NOT NULL;




CREATE TABLE Please (
	ID INT PRIMARY KEY AUTO_INCREMENT, -- 게시판 id
    UUID INT NOT NULL, -- 회원 ID
    Location VARCHAR(50) NOT NULL,
    Up INT NOT NULL DEFAULT 0,
    Views INT NOT NULL DEFAULT 0,
    Tag VARCHAR(50),
    Title VARCHAR(200) NOT NULL,
    Content VARCHAR(2000) NOT NULL,
    inserted DATETIME DEFAULT NOW() NOT NULL,
    updated DATETIME DEFAULT NOW() NOT NULL,
    FOREIGN KEY (UUID) REFERENCES Members (UUID) -- Members 바뀔 수 있음
);
ALTER TABLE Please CHANGE inserted Inserted DATETIME DEFAULT NOW() NOT NULL;
ALTER TABLE Please CHANGE updated Updated DATETIME DEFAULT NOW() NOT NULL;

CREATE TABLE PReply (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    BoardId INT NOT NULL,
    Nickname VARCHAR(50) NOT NULL,
    Reply VARCHAR(500) NOT NULL,
    Inserted DATETIME DEFAULT NOW() NOT NULL,
    Updated DATETIME DEFAULT NOW() NOT NULL,
    FOREIGN KEY (BoardId) REFERENCES Please (ID)
);
ALTER TABLE PReply MODIFY COLUMN Inserted DATETIME DEFAULT NOW() NOT NULL;
ALTER TABLE PReply MODIFY COLUMN Updated DATETIME DEFAULT NOW() NOT NULL;
DESC Please;
DESC Members;
DESC PReply;
